# Generated by Django 4.2.3 on 2023-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="progression",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                ],
                default="A définir",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="balise",
            field=models.CharField(
                choices=[
                    ("Bug", "Bug"),
                    ("Tâche", "Tâche"),
                    ("Amélioration", "Amélioration"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priorite",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                max_length=10,
            ),
        ),
    ]
