# Generated by Django 4.2.3 on 2023-07-25 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_issue_progression_alter_issue_balise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=2048)),
                (
                    "contributeur",
                    models.ForeignKey(
                        default="contributeur inconnu",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.AlterField(
            model_name="issue",
            name="progression",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.issue"
            ),
        ),
    ]
