# Generated by Django 4.2.3 on 2023-07-25 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0003_issuecomment_delete_comment_alter_issue_progression_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="contributeur",
            field=models.ManyToManyField(
                related_name="contributions",
                through="project.IssueComment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
