# Generated by Django 4.2.3 on 2023-08-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
            preserve_default=False,
        ),
    ]
