# Generated by Django 4.2.3 on 2023-08-06 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_issue_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuecomment",
            old_name="contributeur",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="issue",
            name="attribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Utilisateur_attribue",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
