# Generated by Django 4.2.3 on 2023-08-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_rename_contributeur_issuecomment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue",
                to="project.issue",
            ),
        ),
    ]
