# Generated by Django 4.2.3 on 2023-08-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_alter_issuecomment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecomment",
            name="project",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
            preserve_default=False,
        ),
    ]
